DROP TABLE IF EXISTS clubs CASCADE;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS coaches;
DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS clubs_tournaments CASCADE;
DROP TABLE IF EXISTS positions CASCADE;